language: php
php:
  - 7.3
os: linux
dist: bionic
sudo: true

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache
    - bin/.phpunit

stages:
  - name: test
    if: branch = main

jobs:
  include:
    - stage: test
      before_install:
        - cp .env.dist .env.test.local
        - sed -i 's/APP_ENV=dev/APP_ENV=test/' .env.test.local
        - cp .env.test.local .env
        - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
      before_script:
        - composer self-update
        - composer install --no-plugins --no-scripts --no-interaction --prefer-dist --optimize-autoloader
      script:
#        - mkdir -p build/logs
#        - ./bin/phpunit -c phpunit.xml
        - ./bin/phpunit --coverage-clover coverage.xml
      after_success:
        - bash <(curl -s https://codecov.io/bash)
#        - travis_retry php vendor/bin/php-coveralls
